BEGIN;

CREATE TABLE IF NOT EXISTS ROUTES(

    ID TEXT NOT NULL PRIMARY KEY,
    ORIGIN TEXT NOT NULL,
    DESTINATION TEXT,
    DISTANCE INTEGER,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE

);

CREATE TABLE IF NOT EXISTS USERS(

    ID TEXT NOT NULL PRIMARY KEY,
    NAME TEXT NOT NULL,
    LAST_NAME TEXT,
    CITY TEXT,
    ADDRESS TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    FLIGHT TEXT NOT NULL REFERENCES FLIGHTS(ID),
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
    UNIQUE (EMAIL)

);

CREATE TABLE IF NOT EXISTS FLIGHTS(

    ID TEXT NOT NULL PRIMARY KEY,
    ROUTE TEXT NOT NULL REFERENCES ROUTES(ID),
    PLANE TEXT NOT NULL REFERENCES PLANES(ID),
    TAKEOFF_TIME TIMESTAMPTZ,
    LANDING_TIME TIMESTAMPTZ,
    BOARDING_GATE TEXT NOT NULL,
    STATE TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
    UNIQUE (EMAIL)

);

CREATE TABLE IF NOT EXISTS AIRPLANES(

    ID TEXT NOT NULL PRIMARY KEY,
    MODEL TEXT NOT NULL,
    CAPACITY TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE

);

COMMIT;